#!/usr/bin/env python3
"""
Researcher 0 — RESEARCHER
Auto-generated by GENESIS Builder.

Boot sequence: config → modules → BlackZero loader → CognitiveLoop
"""

import sys
from pathlib import Path

# Add GENESIS to path so BlackZero is importable
GENESIS_ROOT = Path(__file__).resolve().parent.parent.parent
if str(GENESIS_ROOT) not in sys.path:
    sys.path.insert(0, str(GENESIS_ROOT))

from BlackZero.loader import boot

if __name__ == "__main__":
    loop = boot("config.yaml", "modules/")
    loop.run()
