# memory_schema.py
# MEMORY SCHEMA DEFINITIONS
#
# Responsibility:
#   Defines the data structures used to represent memories.
#
# What does NOT belong here:
#   - Business logic or memory operations (that belongs in memory_manager.py)
#   - Storage mechanics (that belongs in storage/)

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class MemorySource(str, Enum):
    USER = "user"             # came from direct user input
    TOOL = "tool"             # produced by a tool call
    INFERENCE = "inference"   # generated by the agent's own reasoning
    EXTERNAL = "external"     # imported from an external system


@dataclass
class MemoryRecord:
    """
    A single unit of memory stored and retrieved by the memory system.

    Agents may add fields via subclassing, but must not remove any field
    defined here — all callers in the BlackZero codebase depend on these.
    """
    content: str
    source: MemorySource = MemorySource.INFERENCE
    tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    embedding: list[float] | None = None
    ttl_seconds: int | None = None    # None = permanent
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=datetime.utcnow)

    def is_expired(self) -> bool:
        """Return True if this memory has passed its TTL."""
        if self.ttl_seconds is None:
            return False
        age = (datetime.utcnow() - self.created_at).total_seconds()
        return age > self.ttl_seconds

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "content": self.content,
            "source": self.source.value,
            "tags": self.tags,
            "metadata": self.metadata,
            "ttl_seconds": self.ttl_seconds,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MemoryRecord":
        return cls(
            id=data["id"],
            content=data["content"],
            source=MemorySource(data.get("source", "inference")),
            tags=data.get("tags", []),
            metadata=data.get("metadata", {}),
            ttl_seconds=data.get("ttl_seconds"),
            created_at=datetime.fromisoformat(data["created_at"]),
        )
