"""
Audio API — Serves TTS .wav files generated by VoiceService.
GET /audio/{filename}
"""

from __future__ import annotations

import os
import tempfile

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter(prefix="/audio", tags=["audio"])


@router.get("/{filename}")
async def serve_audio(filename: str):
    """Serve a TTS-generated .wav file from the system temp directory."""
    # Security: only .wav, no path traversal
    if not filename.endswith(".wav") or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=404, detail="Not found")

    filepath = os.path.join(tempfile.gettempdir(), filename)
    if not os.path.isfile(filepath):
        raise HTTPException(status_code=404, detail="Audio file not found")

    return FileResponse(filepath, media_type="audio/wav")
